import { Grid } from "@chakra-ui/react";
import { GetProjects } from "api";
import { SectionWrapper } from "components/wrappers/SectionWrapper";
import type { NextPage } from "next";
import Head from "next/head";
import { useEffect, useState } from "react";

const Home: NextPage = () => {
  const [projects, setProjects] = useState([]);

  useEffect(() => {
    GetProjects().then(({ data }) => {
      setProjects(data);
    });
  }, []);

  useEffect(() => {
    console.log(projects);
  }, [projects]);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SectionWrapper>
        <Grid mt={5}>
          {!!projects.length &&
            projects.map((project: any) => (
              <h1 key={project.ID}>{project.title}</h1>
            ))}
        </Grid>
      </SectionWrapper>
    </div>
  );
};

export default Home;
